[phases.setup]
nixPkgs = ['php', 'php81Packages.composer', 'php81Extensions.mysqli', 'mariadb']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = "php -S 0.0.0.0:9000"